spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wenxiang
    password: bestztZed.1@
    url: jdbc:mysql://118.190.151.71/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell